name: mof
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - pip:
    - argparse
    - colormath
    - cython<3
    - -e git+https://github.com/EwertzJN/fetch-block-construction.git@master#egg=fetch_block_construction
    - gym<=0.17.3
    - mujoco-py 
    - opencv-python
    - pynput
    - tabulate
    - tqdm
    - numpy==1.24.3
